import Link from 'next/link';

export default function AnalystByline() {
  return (
    <aside className="analyst-byline">
      <div className="analyst-byline-avatar" aria-hidden="true">FW</div>
      <div className="analyst-byline-copy">
        <p className="analyst-byline-name">FreeWinningTips Editorial Team</p>
        <p className="analyst-byline-role">
          Football analysts &amp; statistical modelling — East Africa &amp; global leagues
        </p>
        <p className="analyst-byline-text">
          Every FreeWinningTips prediction is generated by our statistical model and reviewed by a
          human analyst before publication. Tips include form, head-to-head patterns, squad news,
          and market movement. Read{' '}
          <Link href="/how-we-predict">how we predict</Link> and check our{' '}
          <Link href="/results">results archive</Link> before following any tip.
        </p>
      </div>
    </aside>
  );
}
